import { z } from "zod";
import { getAIProvider } from "../../../../../lib/ai";
import { draftSchema,type GenerationContext } from "../../../../../lib/ai/types";
import { blocksToText,isVersionConflict,normalizeFacts,parseJson,preserveLocked } from "../../../../../lib/content";
import { copyQualityIssues } from "../../../../../lib/copy-quality";
import { labels } from "../../../../../lib/style";
import { db,json,requireApiUser } from "../../../_shared";
const requestSchema=z.object({versionNo:z.number().int().positive(),blocks:z.array(draftSchema.shape.blocks.element),lockedBlockIds:z.array(z.string()),instruction:z.string().min(1),targetBlockId:z.string().optional()});
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const user=await requireApiUser(request);if(user instanceof Response)return user;const {id}=await params;try{const input=requestSchema.parse(await request.json());const content=await db().prepare("SELECT topic_title,topic_meta,sales_intensity,product_snapshot FROM contents WHERE id=? AND user_id=?").bind(id,user.userId).first<{topic_title:string;topic_meta:string;sales_intensity:number;product_snapshot:string}>();if(!content)return json({error:"内容不存在"},{status:404});const latest=await db().prepare("SELECT MAX(version_no) as maxVersion FROM content_versions WHERE content_id=? AND user_id=?").bind(id,user.userId).first<{maxVersion:number}>();if(latest?.maxVersion!==input.versionNo)return json({error:"此内容已有新版本，请刷新后重试"},{status:409});const style=await db().prepare("SELECT stable_preferences FROM style_dna WHERE user_id=?").bind(user.userId).first<{stable_preferences:string}>();const snapshot=parseJson<{facts?:unknown}>(content.product_snapshot,{}),meta=parseJson<{inspiration?:{angleType?:GenerationContext["angleType"];sources?:GenerationContext["sources"]}}>(content.topic_meta,{}),context:GenerationContext={topic:content.topic_title,facts:normalizeFacts(JSON.stringify(snapshot.facts||[])),salesIntensity:1,stylePreferences:labels(style?.stable_preferences),angleType:meta.inspiration?.angleType||"custom",sources:meta.inspiration?.sources||[]};const ai=getAIProvider();const proposed=await ai.reviseCopy({...context,blocks:input.blocks,lockedBlockIds:input.lockedBlockIds,instruction:input.instruction,targetBlockId:input.targetBlockId});const blocks=preserveLocked(input.blocks,proposed.blocks,input.lockedBlockIds,input.targetBlockId),verification=await ai.verifyCopy(context,{blocks},{blocks:input.blocks});if(!verification.fact_safe)return json({error:`事实检查未通过：${verification.fact_issues.join("；")}`},{status:422});const quality=[...copyQualityIssues({blocks}),...verification.naturalness_issues];if(quality.length)return json({error:`修改后的文案未通过完整性检查：${quality.join("；")}`},{status:422});const versionNo=input.versionNo+1,now=new Date().toISOString();await db().prepare("INSERT INTO content_versions (id,content_id,user_id,version_no,strategy_type,text_content,blocks,locked_block_ids,change_type,change_instruction,is_adopted,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,0,?)").bind(crypto.randomUUID(),id,user.userId,versionNo,"single",blocksToText(blocks),JSON.stringify(blocks),JSON.stringify(input.lockedBlockIds),input.targetBlockId?"block_revision":"full_revision",input.instruction,now).run();await db().prepare("UPDATE contents SET updated_at=? WHERE id=? AND user_id=?").bind(now,id,user.userId).run();return json({versionNo,blocks,verification})}catch(error){if(isVersionConflict(error))return json({error:"此内容已有新版本，请刷新后重试"},{status:409});return json({error:error instanceof Error?error.message:"修改失败，请重试"},{status:422})}}
