"use client";
import { useEffect,useRef,useState } from "react";import { ExternalLink,ImagePlus,Link2,Upload } from "lucide-react";
type Asset={id:string;assetType:string;sourceName:string;imageUrl:string;sourceUrl?:string;author?:string;licenseStatus:string;riskLevel:"green"|"yellow"|"red";metadata:Record<string,unknown>};
export default function AssetLibrary({notify}:{notify:(s:string)=>void}){const [items,setItems]=useState<Asset[]>([]),[files,setFiles]=useState<File[]>([]),[license,setLicense]=useState("owned"),[busy,setBusy]=useState(false),[showLink,setShowLink]=useState(false),[link,setLink]=useState({imageUrl:"",sourceUrl:"",note:""});const input=useRef<HTMLInputElement>(null);const load=()=>fetch("/api/assets").then(r=>r.json() as Promise<Asset[]>).then(setItems).catch(()=>notify("素材读取失败"));useEffect(()=>{void load()},[]);
async function upload(){if(!files.length)return;setBusy(true);const form=new FormData();files.forEach(file=>form.append("files",file));form.set("licenseType",license);const r=await fetch("/api/assets/batch",{method:"POST",body:form}),data=await r.json() as {error?:string;items?:Array<{duplicate:boolean}>};if(r.ok){notify(data.items?.some(x=>x.duplicate)?"已上传，重复图片已自动跳过":"图片已安全保存");setFiles([]);await load()}else notify(data.error||"上传失败");setBusy(false)}
async function addLink(){const r=await fetch("/api/assets/external",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(link)}),data=await r.json() as {error?:string};if(r.ok){setLink({imageUrl:"",sourceUrl:"",note:""});setShowLink(false);await load();notify("外部图片链接已保存")}else notify(data.error||"保存失败")}
async function risk(id:string,riskLevel:Asset["riskLevel"]){await fetch(`/api/assets/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({riskLevel})});await load()}
return <div className="page-wrap"><header className="page-header"><div><p className="kicker">真实图片素材</p><h1>为下一条内容找画面</h1></div><div className="asset-top-actions"><button className="secondary-button" onClick={()=>setShowLink(v=>!v)}><Link2 size={17}/>外部链接</button><button className="primary-button" onClick={()=>input.current?.click()}><Upload size={17}/>选择图片</button></div></header><input ref={input} hidden multiple type="file" accept="image/*" onChange={e=>setFiles([...e.target.files||[]])}/>
{files.length>0&&<section className="batch-upload"><div><strong>已选择 {files.length} 张图片</strong><p>同一批图片使用统一授权状态</p></div><select value={license} onChange={e=>setLicense(e.target.value)}><option value="owned">本人/公司拍摄</option><option value="authorized">已获得授权</option><option value="purchased">商业购买素材</option><option value="other">其他</option></select><button className="primary-button" disabled={busy} onClick={upload}>{busy?"上传中…":"确认上传"}</button></section>}
{showLink&&<section className="external-form"><input placeholder="图片 URL" value={link.imageUrl} onChange={e=>setLink({...link,imageUrl:e.target.value})}/><input placeholder="来源页面" value={link.sourceUrl} onChange={e=>setLink({...link,sourceUrl:e.target.value})}/><input placeholder="备注" value={link.note} onChange={e=>setLink({...link,note:e.target.value})}/><button className="primary-button" onClick={addLink}>保存链接</button></section>}
<div className="real-asset-grid">{items.map(asset=><article className="real-asset-card" key={asset.id}><div className="asset-photo">{asset.imageUrl?<img src={asset.imageUrl} alt={asset.sourceName}/>:<ImagePlus/>}<span className={`risk-dot ${asset.riskLevel}`}>{asset.riskLevel==="green"?"绿色":asset.riskLevel==="yellow"?"黄色":"红色"}</span></div><div className="real-asset-info"><strong>{asset.sourceName}</strong><small>{asset.assetType==="pexels"?`Photo by ${asset.author} on Pexels`:asset.assetType==="external_link"?"外部链接":"本人素材"}</small>{asset.sourceUrl&&<a href={asset.sourceUrl} target="_blank" rel="noreferrer">查看来源 <ExternalLink size={13}/></a>}<select value={asset.riskLevel} onChange={e=>risk(asset.id,e.target.value as Asset["riskLevel"])}><option value="green">绿色风险</option><option value="yellow">黄色风险</option><option value="red">红色风险</option></select></div></article>)}</div>
{!items.length&&<div className="empty-hint"><ImagePlus/><div><strong>还没有图片素材</strong><p>上传自己的照片，或添加有明确来源的图片链接。</p></div></div>}<p className="rights-notice">绿色表示平台或授权条件层面可用，但不代表图片中的人物、商标、艺术品或场地等第三方权利一定不存在。</p></div>}
