"use client";
import { useEffect,useRef,useState } from "react";
import { Crop,LoaderCircle,Minus,Plus,X } from "lucide-react";
import { readApiError } from "@/lib/friendly-error";
type CroppedAsset={id:string;sourceName:string;imageUrl:string;riskLevel:string;assetType:string};
const SIZE=1200;
export default function ImageCropper({asset,onCancel,onSaved}:{asset:{id:string;sourceName:string;imageUrl:string};onCancel:()=>void;onSaved:(asset:CroppedAsset)=>void}){
 const canvasRef=useRef<HTMLCanvasElement>(null),imageRef=useRef<HTMLImageElement|null>(null),dragRef=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
 const [zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 function clamp(next:{x:number;y:number},atZoom=zoom){const image=imageRef.current;if(!image)return{x:0,y:0};const scale=Math.max(SIZE/image.naturalWidth,SIZE/image.naturalHeight)*atZoom,maxX=Math.max(0,(image.naturalWidth*scale-SIZE)/2),maxY=Math.max(0,(image.naturalHeight*scale-SIZE)/2);return{x:Math.max(-maxX,Math.min(maxX,next.x)),y:Math.max(-maxY,Math.min(maxY,next.y))}}
 function changeZoom(next:number){setZoom(next);setOffset(current=>clamp(current,next))}
 useEffect(()=>{const image=new Image();image.onload=()=>{imageRef.current=image;setOffset({x:0,y:0})};image.onerror=()=>setError("图片读取失败，请返回素材库重新上传。");image.src=asset.imageUrl},[asset.imageUrl]);
 useEffect(()=>{const canvas=canvasRef.current,image=imageRef.current;if(!canvas||!image)return;const scale=Math.max(SIZE/image.naturalWidth,SIZE/image.naturalHeight)*zoom,drawWidth=image.naturalWidth*scale,drawHeight=image.naturalHeight*scale,context=canvas.getContext("2d");if(!context)return;context.clearRect(0,0,SIZE,SIZE);context.drawImage(image,(SIZE-drawWidth)/2+offset.x,(SIZE-drawHeight)/2+offset.y,drawWidth,drawHeight)},[zoom,offset]);
 function pointerMove(event:React.PointerEvent<HTMLCanvasElement>){const drag=dragRef.current,canvas=canvasRef.current;if(!drag||!canvas)return;const ratio=SIZE/canvas.getBoundingClientRect().width;setOffset(clamp({x:drag.ox+(event.clientX-drag.x)*ratio,y:drag.oy+(event.clientY-drag.y)*ratio}))}
 async function save(){const canvas=canvasRef.current;if(!canvas)return;setBusy(true);setError("");try{const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.92));if(!blob)throw new Error("裁切图片生成失败");const base=asset.sourceName.replace(/\.[^.]+$/,""),form=new FormData();form.append("file",new File([blob],`${base}-朋友圈方图.jpg`,{type:"image/jpeg"}));const response=await fetch(`/api/assets/${asset.id}/crop`,{method:"POST",body:form});if(!response.ok){setError(await readApiError(response,"裁切图片保存失败，请重试。"));return}const result=await response.json() as {id:string;sourceName:string};onSaved({id:result.id,sourceName:result.sourceName,imageUrl:`/api/assets/${result.id}/file`,riskLevel:"green",assetType:"user_upload"})}catch(reason){setError(reason instanceof Error?reason.message:"裁切图片保存失败，请重试。")}finally{setBusy(false)}}
 return <div className="cropper-backdrop" onClick={onCancel}><section className="cropper-dialog" role="dialog" aria-modal="true" aria-label="裁切朋友圈配图" onClick={event=>event.stopPropagation()}><header><div><span className="mini-label">朋友圈配图裁切</span><h2>把主体放进正方形画面</h2></div><button onClick={onCancel} aria-label="关闭裁切"><X/></button></header><p className="cropper-hint">已自动居中。拖动图片调整主体位置，必要时缩放，网格交点可辅助构图。原图会保留。</p><div className="cropper-stage"><canvas ref={canvasRef} width={SIZE} height={SIZE} onPointerDown={event=>{dragRef.current={x:event.clientX,y:event.clientY,ox:offset.x,oy:offset.y};event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={pointerMove} onPointerUp={()=>{dragRef.current=null}} onPointerCancel={()=>{dragRef.current=null}}/></div><div className="cropper-controls"><button onClick={()=>changeZoom(Math.max(1,Number((zoom-.1).toFixed(1))))} disabled={zoom<=1} aria-label="缩小"><Minus/></button><input type="range" min="1" max="2.5" step="0.05" value={zoom} onChange={event=>changeZoom(Number(event.target.value))} aria-label="图片缩放"/><button onClick={()=>changeZoom(Math.min(2.5,Number((zoom+.1).toFixed(1))))} disabled={zoom>=2.5} aria-label="放大"><Plus/></button><span>{Math.round(zoom*100)}%</span></div>{error&&<p className="analysis-error" role="alert">{error}</p>}<footer><button className="secondary-button" onClick={()=>{setZoom(1);setOffset({x:0,y:0})}}>恢复居中</button><button className="primary-button" disabled={busy} onClick={save}>{busy?<LoaderCircle className="spin" size={17}/>:<Crop size={17}/>}保存为朋友圈方图</button></footer></section></div>
}
