"use client";
import { useEffect,useState } from "react";import { Check,ChevronDown,Dna,ThumbsDown,ThumbsUp,Trash2 } from "lucide-react";
import { readApiError } from "@/lib/friendly-error";
type Pref={id:string;label:string;confidence:number;evidenceCount:number;flexible:boolean};type Data={onboarding:{styleSetup?:boolean};stable:Pref[];candidates:Pref[];negative:string[];evidenceSummary:Record<string,unknown>};const dislikes=[["strong_sales","强销售感"],["too_trendy","网络流行语过多"],["too_emotional","情绪过度"],["too_official","太官方"],["too_long","长篇大论"],["too_many_emoji","Emoji太多"]];
export default function StyleDNA({notify}:{notify:(s:string)=>void}){const [data,setData]=useState<Data|null>(null),[loadError,setLoadError]=useState(""),[identity,setIdentity]=useState("balanced"),[selected,setSelected]=useState<string[]>([]);
async function load(){try{const r=await fetch("/api/style");if(!r.ok){setLoadError(await readApiError(r,"风格数据读取失败，请稍后重试。"));return}setData(await r.json() as Data);setLoadError("")}catch{setLoadError("风格数据读取失败，请稍后重试。")}}
useEffect(()=>{void (async()=>{await load()})()},[]);async function setup(){const r=await fetch("/api/style",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identity,dislikes:selected})});if(r.ok){await load();notify("初始偏好已保存，之后会随采用内容逐步调整")}}async function action(id:string,act:string){await fetch("/api/style",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action:act})});await load()}if(loadError)return <div className="page-wrap narrow"><header className="page-header"><div><p className="kicker">我的风格</p><h1>让文字慢慢更像你</h1></div></header><p className="analysis-error" role="alert">{loadError}</p></div>;
if(!data)return <div className="page-wrap narrow"><p>正在读取你的风格…</p></div>;
if(!data.onboarding?.styleSetup)return <div className="page-wrap narrow"><header className="page-header"><div><p className="kicker">一分钟轻设置</p><h1>先给 Style DNA 一个起点</h1></div></header><section className="style-setup"><div><label>希望别人更容易觉得你是</label><div className="identity-options">{[["advisor","很懂欧洲的旅行顾问"],["discoverer","很会发现旅行乐趣的人"],["balanced","两者都有"]].map(([v,l])=><button className={identity===v?"active":""} onClick={()=>setIdentity(v)} key={v}>{l}{identity===v&&<Check size={16}/>}</button>)}</div></div><div><label>比较不喜欢（可多选）</label><div className="dislike-options">{dislikes.map(([v,l])=><button className={selected.includes(v)?"active":""} onClick={()=>setSelected(x=>x.includes(v)?x.filter(y=>y!==v):[...x,v])} key={v}>{l}</button>)}</div></div><button className="primary-button" onClick={setup}>保存初始偏好</button><p>这些只是起点，不是永久结论。系统只会在你采用最终文案后学习一次。</p></section></div>;
return <div className="page-wrap narrow"><header className="page-header"><div><p className="kicker">我的风格</p><h1>让文字慢慢更像你</h1></div><span className="dna-status"><Dna size={17}/>渐进学习中</span></header><section className="dna-summary"><strong>学习原则</strong><p>约 70% 遵循已确认习惯，同时保留合理变化。风格偏好不会被当作产品事实。</p></section><section className="preference-section"><div className="section-heading"><div><span>已经比较确定</span><h2>{data.stable.length?`${data.stable.length} 条稳定偏好`:"还没有稳定偏好"}</h2></div></div><div className="preference-list">{data.stable.map(pref=><article key={pref.id}><div><strong>{pref.label}</strong><small>{pref.flexible?"弹性偏好":"稳定原则"} · {pref.evidenceCount} 次证据</small></div><div><button onClick={()=>action(pref.id,"keep")}><Check size={15}/>保留</button><button onClick={()=>action(pref.id,"lower")}><ChevronDown size={15}/>降低权重</button><button onClick={()=>action(pref.id,"delete")}><Trash2 size={15}/>删除</button></div></article>)}</div></section><section className="preference-section"><div className="section-heading"><div><span>正在学习</span><h2>{data.candidates.length?`${data.candidates.length} 条候选偏好`:"等待新的采用记录"}</h2></div></div><div className="preference-list learning">{data.candidates.map(pref=><article key={pref.id}><div><strong>可能{pref.label}</strong><small>置信度 {Math.round(pref.confidence*100)}% · {pref.evidenceCount} 次证据</small></div><div><button onClick={()=>action(pref.id,"accurate")}><ThumbsUp size={15}/>准确</button><button onClick={()=>action(pref.id,"wrong")}><ThumbsDown size={15}/>不对</button></div></article>)}</div></section>{data.negative.length>0&&<section className="negative-note"><strong>已排除的判断</strong><p>{data.negative.join(" · ")}</p></section>}</div>}
